In [98]:
#import sys 

#!{sys.executable} -m pip install pandas numpy matplotlib scikit-learn

In [99]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [100]:
df = pd.read_csv("diabetes_prediction_dataset.csv")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  str
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  str
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), str(2)
memory usage: 6.9 MB

In [101]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [ ]:
feature_list = list(df.columns)
print(feature_list)

['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes']

In [ ]:

value_types = {}

for df_column in list(df.columns).pop():
  for elem in df[df_column]:
    if elem in value_types:
      value_types[elem] += 1
    else:
      value_types[elem] = 1

value_types

{0: 338625,
 1: 61440,
 2: 1204,
 80.0: 12727,
 54.0: 1509,
 28.0: 1465,
 36.0: 1299,
 76.0: 733,
 20.0: 1284,
 44.0: 1414,
 79.0: 621,
 42.0: 1405,
 32.0: 1298,
 53.0: 1543,
 78.0: 682,
 67.0: 1040,
 15.0: 1001,
 37.0: 1350,
 40.0: 1413,
 5.0: 8464,
 69.0: 966,
 72.0: 790,
 4.0: 8495,
 30.0: 1351,
 45.0: 1476,
 43.0: 1451,
 50.0: 1461,
 41.0: 1315,
 26.0: 1362,
 34.0: 1300,
 73.0: 823,
 77.0: 730,
 66.0: 1176,
 29.0: 1425,
 60.0: 1424,
 38.0: 1527,
 3.0: 1038,
 57.0: 1521,
 74.0: 764,
 19.0: 1311,
 46.0: 1534,
 21.0: 1324,
 59.0: 1399,
 27.0: 1373,
 13.0: 949,
 56.0: 1435,
 7.0: 1537,
 11.0: 845,
 6.0: 9226,
 55.0: 1504,
 9.0: 1435,
 62.0: 1474,
 47.0: 1580,
 12.0: 893,
 68.0: 978,
 75.0: 721,
 22.0: 1308,
 58.0: 1349,
 18.0: 1223,
 24.0: 1325,
 17.0: 1055,
 25.0: 1348,
 0.08: 36,
 33.0: 1308,
 16.0: 1052,
 61.0: 1403,
 31.0: 1327,
 8.0: 876,
 49.0: 1544,
 39.0: 1433,
 65.0: 1134,
 14.0: 920,
 70.0: 919,
 0.56: 96,
 48.0: 1574,
 51.0: 1620,
 71.0: 871,
 0.88: 90,
 64.0: 1098,
 63.0: 1089,
 52.0: 1534,
 0.16: 59,
 10.0: 860,
 35.0: 1261,
 23.0: 1356,
 0.64: 99,
 1.16: 89,
 1.64: 118,
 0.72: 104,
 1.88: 86,
 1.32: 103,
 0.8: 102,
 1.24: 90,
 1.8: 108,
 0.48: 83,
 1.56: 113,
 1.08: 95,
 0.24: 87,
 1.4: 101,
 0.4: 66,
 0.32: 89,
 1.72: 97,
 1.48: 107,
 'never': 35095,
 'No Info': 35816,
 'current': 9286,
 'former': 9352,
 'ever': 4004,
 'not current': 6447,
 25.19: 29,
 27.32: 25495,
 23.45: 30,
 20.14: 29,
 19.31: 26,
 23.86: 61,
 33.64: 39,
 54.7: 2,
 36.05: 11,
 25.69: 65,
 30.36: 33,
 24.48: 51,
 25.72: 51,
 36.38: 13,
 18.8: 26,
 21.24: 23,
 27.94: 51,
 13.99: 6,
 33.76: 32,
 27.85: 22,
 26.47: 57,
 26.08: 59,
 31.75: 58,
 25.15: 83,
 22.01: 37,
 22.19: 46,
 23.55: 38,
 15.1: 30,
 21.76: 28,
 21.22: 47,
 56.43: 2,
 25.91: 17,
 32.02: 13,
 29.3: 59,
 24.93: 46,
 19.95: 19,
 18.03: 17,
 28.27: 43,
 19.27: 24,
 28.12: 51,
 23.05: 48,
 37.16: 24,
 23.35: 22,
 24.41: 47,
 63.48: 1,
 27.86: 64,
 26.1: 47,
 30.22: 50,
 23.11: 60,
 28.16: 50,
 26.78: 51,
 23.04: 59,
 15.94: 22,
 15.8: 32,
 27.01: 32,
 27.45: 53,
 17.98: 11,
 26.45: 40,
 31.16: 32,
 24.42: 53,
 30.5: 34,
 26.37: 18,
 31.86: 26,
 21.25: 35,
 30.95: 32,
 31.19: 13,
 32.27: 20,
 22.42: 19,
 16.39: 25,
 17.46: 29,
 37.35: 5,
 32.85: 26,
 55.61: 1,
 50.13: 4,
 18.6: 35,
 24.18: 35,
 37.26: 17,
 19.39: 25,
 31.21: 37,
 21.12: 33,
 27.14: 48,
 20.6: 64,
 34.2: 34,
 27.63: 52,
 20.3: 72,
 18.67: 30,
 20.9: 70,
 20.41: 20,
 16.76: 19,
 15.06: 14,
 31.7: 52,
 28.73: 79,
 25.18: 70,
 25.77: 33,
 36.53: 15,
 27.59: 13,
 26.79: 40,
 35.55: 13,
 22.06: 11,
 36.49: 22,
 27.8: 100,
 23.76: 37,
 44.06: 4,
 21.97: 52,
 29.4: 68,
 20.16: 52,
 30.8: 44,
 22.95: 60,
 33.22: 28,
 27.93: 27,
 29.6: 87,
 14.43: 10,
 26.72: 71,
 41.24: 5,
 34.87: 21,
 23.96: 69,
 36.27: 25,
 29.06: 28,
 30.85: 33,
 17.61: 26,
 27.7: 69,
 19.21: 30,
 22.34: 29,
 29.59: 11,
 35.44: 26,
 39.36: 5,
 27.39: 59,
 31.9: 36,
 26.61: 25,
 23.08: 55,
 25.84: 86,
 25.8: 50,
 26.02: 18,
 23.56: 44,
 24.65: 21,
 25.11: 46,
 30.37: 32,
 21.54: 38,
 40.9: 16,
 26.7: 94,
 42.24: 5,
 23.93: 33,
 15.48: 10,
 26.71: 25,
 28.25: 33,
 30.68: 34,
 36.96: 13,
 23.59: 26,
 32.81: 30,
 35.15: 30,
 29.41: 30,
 22.17: 18,
 27.5: 70,
 29.95: 76,
 26.57: 68,
 21.78: 37,
 20.89: 32,
 16.85: 18,
 13.79: 4,
 26.04: 53,
 34.31: 23,
 28.22: 57,
 36.73: 14,
 32.92: 35,
 21.46: 45,
 29.28: 44,
 17.09: 30,
 25.31: 26,
 28.89: 55,
 31.2: 40,
 17.49: 25,
 27.77: 51,
 32.31: 35,
 15.57: 22,
 20.38: 45,
 22.35: 35,
 29.34: 23,
 24.88: 34,
 20.56: 27,
 35.06: 9,
 22.3: 75,
 23.49: 58,
 38.08: 17,
 23.25: 16,
 18.2: 47,
 13.57: 5,
 29.25: 25,
 24.36: 86,
 12.15: 2,
 30.05: 24,
 15.29: 12,
 26.96: 32,
 22.29: 33,
 39.3: 18,
 32.62: 18,
 24.29: 58,
 24.19: 33,
 27.4: 58,
 21.06: 63,
 25.29: 41,
 21.83: 21,
 33.83: 29,
 32.6: 37,
 24.3: 74,
 23.71: 54,
 19.6: 51,
 20.53: 9,
 20.19: 46,
 27.07: 36,
 30.55: 30,
 14.69: 16,
 24.81: 34,
 20.91: 33,
 27.25: 42,
 36.54: 14,
 21.3: 93,
 25.25: 51,
 23.75: 29,
 26.4: 79,
 33.36: 19,
 35.35: 14,
 21.43: 26,
 29.49: 50,
 20.08: 43,
 20.67: 75,
 39.46: 14,
 36.18: 31,
 43.14: 2,
 21.66: 34,
 27.82: 53,
 16.96: 21,
 35.49: 29,
 15.7: 18,
 17.47: 15,
 23.88: 38,
 26.35: 20,
 19.9: 26,
 37.59: 14,
 25.4: 76,
 30.41: 50,
 37.07: 15,
 22.48: 50,
 24.62: 61,
 31.88: 31,
 50.3: 7,
 25.21: 31,
 27.09: 36,
 35.24: 29,
 35.13: 22,
 14.9: 15,
 26.07: 32,
 23.9: 57,
 24.78: 69,
 30.71: 45,
 32.37: 18,
 24.34: 31,
 26.39: 50,
 25.46: 61,
 29.2: 54,
 28.37: 30,
 26.62: 70,
 39.29: 14,
 48.02: 4,
 32.2: 51,
 51.76: 5,
 22.6: 56,
 15.65: 21,
 24.03: 47,
 32.61: 43,
 36.3: 11,
 17.1: 38,
 19.47: 36,
 31.57: 30,
 25.41: 25,
 22.43: 47,
 20.98: 68,
 14.35: 10,
 17.13: 21,
 24.02: 38,
 33.26: 23,
 17.68: 21,
 26.25: 84,
 16.59: 25,
 20.12: 43,
 31.28: 51,
 26.32: 41,
 37.8: 12,
 37.5: 30,
 29.08: 36,
 38.64: 3,
 25.23: 25,
 38.14: 7,
 40.31: 19,
 22.73: 28,
 45.99: 2,
 16.02: 18,
 24.56: 30,
 22.83: 31,
 21.04: 25,
 22.66: 34,
 40.02: 20,
 33.19: 25,
 15.9: 28,
 24.22: 50,
 22.94: 33,
 26.97: 37,
 30.83: 41,
 21.88: 32,
 22.4: 99,
 18.56: 28,
 25.97: 45,
 43.42: 14,
 17.11: 25,
 26.53: 64,
 31.53: 37,
 23.44: 15,
 28.49: 47,
 31.79: 36,
 21.05: 28,
 25.68: 68,
 18.27: 21,
 21.29: 33,
 17.97: 48,
 30.73: 26,
 36.12: 13,
 35.91: 25,
 21.52: 42,
 23.65: 70,
 37.24: 20,
 28.66: 45,
 25.37: 42,
 22.38: 67,
 16.53: 20,
 24.1: 70,
 19.15: 30,
 19.7: 32,
 23.15: 28,
 26.87: 43,
 15.78: 20,
 23.91: 57,
 36.17: 8,
 29.93: 41,
 28.82: 46,
 15.64: 16,
 33.2: 40,
 31.12: 55,
 46.12: 3,
 22.53: 34,
 26.88: 64,
 18.22: 14,
 22.18: 26,
 19.82: 31,
 15.74: 20,
 32.19: 39,
 28.59: 29,
 33.95: 20,
 29.44: 35,
 28.35: 77,
 36.47: 19,
 22.57: 39,
 16.55: 15,
 21.2: 46,
 14.73: 6,
 41.01: 5,
 32.18: 24,
 34.3: 37,
 26.27: 23,
 36.93: 16,
 31.84: 12,
 24.55: 24,
 20.93: 29,
 27.12: 101,
 25.67: 25,
 30.12: 34,
 24.77: 34,
 40.59: 12,
 25.48: 38,
 16.34: 27,
 18.48: 23,
 21.7: 76,
 21.15: 17,
 20.28: 37,
 26.93: 32,
 24.4: 56,
 15.69: 11,
 25.44: 26,
 36.8: 23,
 31.85: 26,
 32.88: 17,
 24.21: 67,
 36.11: 9,
 69.37: 1,
 39.17: 11,
 16.73: 18,
 37.78: 4,
 27.89: 48,
 22.55: 58,
 36.74: 11,
 26.46: 57,
 29.22: 24,
 31.01: 66,
 14.79: 20,
 15.44: 15,
 23.24: 83,
 35.07: 25,
 25.42: 56,
 22.46: 52,
 28.34: 60,
 19.57: 21,
 21.85: 33,
 20.18: 11,
 17.08: 15,
 24.15: 23,
 34.52: 10,
 41.65: 10,
 22.51: 23,
 23.47: 39,
 16.5: 45,
 22.39: 46,
 27.04: 44,
 31.17: 32,
 17.64: 33,
 43.79: 4,
 20.59: 38,
 36.31: 26,
 48.2: 2,
 20.8: 64,
 60.26: 1,
 19.52: 16,
 27.22: 90,
 40.86: 2,
 16.21: 20,
 37.2: 19,
 33.04: 25,
 22.84: 38,
 17.3: 37,
 19.14: 20,
 20.24: 18,
 29.98: 25,
 25.9: 58,
 27.83: 53,
 18.97: 25,
 35.63: 19,
 24.35: 18,
 35.56: 25,
 22.32: 93,
 35.75: 12,
 18.78: 25,
 44.38: 4,
 29.54: 23,
 42.57: 9,
 31.99: 32,
 25.52: 43,
 38.5: 16,
 25.34: 51,
 31.72: 15,
 29.02: 28,
 21.03: 32,
 28.94: 40,
 30.38: 56,
 37.3: 25,
 43.41: 10,
 24.89: 71,
 16.77: 18,
 10.3: 2,
 34.24: 26,
 23.48: 32,
 23.97: 37,
 15.66: 20,
 16.67: 13,
 28.48: 31,
 17.5: 35,
 22.21: 40,
 16.69: 21,
 33.08: 44,
 21.81: 35,
 23.06: 18,
 27.27: 35,
 42.4: 6,
 35.42: 37,
 49.27: 5,
 25.94: 89,
 31.31: 32,
 23.46: 27,
 23.87: 45,
 21.75: 16,
 27.3: 64,
 28.51: 46,
 28.72: 29,
 26.91: 33,
 34.63: 8,
 24.33: 47,
 19.03: 10,
 15.97: 34,
 25.04: 16,
 18.1: 29,
 23.33: 69,
 28.99: 50,
 25.05: 68,
 22.96: 61,
 29.26: 53,
 24.7: 47,
 31.59: 48,
 30.58: 22,
 22.31: 63,
 20.09: 36,
 30.49: 47,
 26.2: 44,
 25.39: 61,
 16.92: 15,
 20.95: 32,
 27.99: 35,
 49.23: 2,
 33.7: 24,
 34.17: 26,
 27.52: 33,
 36.58: 29,
 17.25: 11,
 27.73: 44,
 42.54: 3,
 23.5: 53,
 21.33: 41,
 35.1: 16,
 21.72: 24,
 30.84: 40,
 19.34: 25,
 28.42: 51,
 25.63: 44,
 24.11: 45,
 32.95: 33,
 24.46: 67,
 19.46: 41,
 20.4: 32,
 15.62: 22,
 26.12: 48,
 18.42: 23,
 18.51: 21,
 33.45: 27,
 14.7: 19,
 37.13: 7,
 11.16: 2,
 44.5: 5,
 16.22: 19,
 30.21: 45,
 30.09: 45,
 22.04: 25,
 33.72: 29,
 33.16: 10,
 34.54: 31,
 36.61: 37,
 28.96: 13,
 26.6: 79,
 22.65: 36,
 18.75: 33,
 16.28: 15,
 23.29: 47,
 34.02: 21,
 24.96: 100,
 37.9: 31,
 25.76: 51,
 19.22: 39,
 29.79: 31,
 19.97: 30,
 28.19: 50,
 36.87: 5,
 37.83: 14,
 20.51: 13,
 36.4: 19,
 27.02: 63,
 25.95: 32,
 37.53: 2,
 33.56: 19,
 31.25: 22,
 36.01: 22,
 27.98: 64,
 32.44: 28,
 22.36: 21,
 29.64: 45,
 26.15: 59,
 29.15: 45,
 34.13: 34,
 24.92: 25,
 42.48: 7,
 35.83: 22,
 22.14: 62,
 31.68: 26,
 24.71: 52,
 38.36: 11,
 39.9: 6,
 21.91: 16,
 22.13: 55,
 13.95: 11,
 21.13: 43,
 15.24: 20,
 16.87: 23,
 15.33: 22,
 16.7: 50,
 28.87: 40,
 33.14: 34,
 20.88: 34,
 25.7: 59,
 17.07: 21,
 18.23: 16,
 20.78: 30,
 28.75: 36,
 28.6: 50,
 29.35: 35,
 24.38: 25,
 21.6: 47,
 27.6: 53,
 23.28: 28,
 34.03: 26,
 29.92: 29,
 18.49: 22,
 18.02: 23,
 17.53: 19,
 40.37: 6,
 31.94: 28,
 32.84: 30,
 54.12: 3,
 22.64: 27,
 20.94: 28,
 24.27: 78,
 33.63: 20,
 17.37: 12,
 26.56: 39,
 16.3: 33,
 30.45: 42,
 46.07: 6,
 31.44: 47,
 38.25: 13,
 30.28: 29,
 30.54: 42,
 21.9: 37,
 16.36: 26,
 24.66: 22,
 34.42: 21,
 18.16: 12,
 31.34: 18,
 17.28: 33,
 29.01: 51,
 24.5: 94,
 26.49: 33,
 24.44: 44,
 44.23: 2,
 26.06: 31,
 32.12: 41,
 24.69: 58,
 21.35: 22,
 18.93: 17,
 26.17: 66,
 19.76: 29,
 38.95: 14,
 33.58: 13,
 19.69: 39,
 24.2: 54,
 31.76: 21,
 27.19: 46,
 37.4: 14,
 19.51: 23,
 24.9: 66,
 20.47: 16,
 17.58: 20,
 27.34: 32,
 21.79: 61,
 23.1: 67,
 30.65: 42,
 31.82: 42,
 20.04: 27,
 31.46: 34,
 25.06: 70,
 24.37: 36,
 14.31: 6,
 39.45: 8,
 41.76: 5,
 40.81: 5,
 24.76: 30,
 13.12: 7,
 11.85: 1,
 28.15: 33,
 25.54: 46,
 28.4: 55,
 34.09: 18,
 34.57: 30,
 22.9: 57,
 31.4: 41,
 31.56: 44,
 17.86: 16,
 36.03: 23,
 28.45: 93,
 16.6: 41,
 32.89: 35,
 34.8: 23,
 15.28: 27,
 25.98: 43,
 15.45: 15,
 10.77: 2,
 43.16: 6,
 31.08: 15,
 29.63: 51,
 16.24: 23,
 32.26: 29,
 41.14: 2,
 18.3: 35,
 20.76: 10,
 17.84: 21,
 23.32: 65,
 21.4: 36,
 22.71: 52,
 21.63: 77,
 27.43: 35,
 43.75: 5,
 25.2: 90,
 25.49: 48,
 40.5: 18,
 28.07: 55,
 15.86: 19,
 25.3: 44,
 24.06: 22,
 24.67: 22,
 32.57: 51,
 42.44: 13,
 38.81: 3,
 30.2: 43,
 29.29: 93,
 26.21: 47,
 18.38: 22,
 26.42: 27,
 33.6: 34,
 32.32: 17,
 19.87: 39,
 34.15: 24,
 26.29: 37,
 33.41: 29,
 20.66: 40,
 57.17: 2,
 23.37: 24,
 31.61: 27,
 22.76: 72,
 45.7: 8,
 19.81: 32,
 27.76: 63,
 37.72: 2,
 40.01: 5,
 45.03: 6,
 23.95: 20,
 39.2: 28,
 44.24: 8,
 15.43: 13,
 22.61: 32,
 48.61: 1,
 40.39: 8,
 23.43: 72,
 23.8: 76,
 40.77: 13,
 37.02: 21,
 27.92: 36,
 28.52: 17,
 32.9: 58,
 50.36: 3,
 38.75: 9,
 30.23: 66,
 38.42: 14,
 26.83: 47,
 23.12: 30,
 38.66: 13,
 23.63: 75,
 18.84: 23,
 19.8: 42,
 15.36: 22,
 20.2: 38,
 13.02: 3,
 33.51: 14,
 30.98: 40,
 24.99: 27,
 29.68: 26,
 33.37: 24,
 31.27: 29,
 32.08: 15,
 19.74: 33,
 40.67: 13,
 33.84: 15,
 29.83: 25,
 31.48: 25,
 15.88: 18,
 17.87: 15,
 36.06: 15,
 29.16: 44,
 13.66: 5,
 29.1: 41,
 38.04: 14,
 26.36: 52,
 27.18: 28,
 36.09: 15,
 20.75: 65,
 29.05: 78,
 33.3: 42,
 29.86: 40,
 18.28: 10,
 40.21: 4,
 28.58: 42,
 21.64: 30,
 26.51: 21,
 38.91: 8,
 60.2: 2,
 22.08: 32,
 28.3: 36,
 43.81: 2,
 25.88: 37,
 29.53: 49,
 28.98: 41,
 36.71: 17,
 16.12: 18,
 34.27: 17,
 17.9: 32,
 21.94: 18,
 25.71: 21,
 31.15: 31,
 29.23: 60,
 30.06: 42,
 21.51: 25,
 27.08: 14,
 25.53: 38,
 26.31: 72,
 20.27: 30,
 19.42: 32,
 22.68: 79,
 21.14: 52,
 18.4: 37,
 23.57: 36,
 18.24: 31,
 20.64: 21,
 19.16: 20,
 21.47: 16,
 38.24: 18,
 48.57: 4,
 22.59: 44,
 31.63: 37,
 38.97: 11,
 23.2: 64,
 30.34: 50,
 33.86: 25,
 16.15: 22,
 32.94: 19,
 13.91: 3,
 25.45: 36,
 21.8: 84,
 19.29: 27,
 28.14: 31,
 16.37: 19,
 18.86: 17,
 27.26: 43,
 22.92: 49,
 34.76: 14,
 15.81: 24,
 21.95: 61,
 20.96: 13,
 15.03: 19,
 28.57: 37,
 25.64: 46,
 18.82: 25,
 35.48: 17,
 31.32: 49,
 37.75: 11,
 21.34: 20,
 19.38: 21,
 26.76: 39,
 34.85: 38,
 30.53: 58,
 15.46: 20,
 32.39: 12,
 28.8: 75,
 30.56: 36,
 32.07: 44,
 33.75: 25,
 45.19: 6,
 21.71: 73,
 25.61: 16,
 21.67: 24,
 29.99: 55,
 28.23: 27,
 14.18: 6,
 28.2: 43,
 15.54: 16,
 25.01: 27,
 25.82: 52,
 34.11: 27,
 21.38: 67,
 29.55: 55,
 18.92: 18,
 27.61: 24,
 ...}

In [ ]:
#Converting non numerical data into numerical data

#Females = 0 , Male = 1
mapping = {"Female": 0, "Male": 1, "Other": 2}
df["gender"] = df["gender"].map(mapping)

df["gender"].fillna(2).astype("int")




df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,never,25.19,6.6,140,0
1,0,54.0,0,0,No Info,27.32,6.6,80,0
2,1,28.0,0,0,never,27.32,5.7,158,0
3,0,36.0,0,0,current,23.45,5.0,155,0
4,1,76.0,1,1,current,20.14,4.8,155,0

In [104]:
df["gender"].isna().sum()

np.int64(0)